.build_template:
    stage: build
    variables: 
        IMAGE_BUILD: ""
        ENVS: ""
    script:
        - docker build --pull -f Dockerfile -t $IMAGE_BUILD .
        - docker push $IMAGE_BUILD
